prometheusOperator:
  nodeSelector:
    agentpool: monitoring
  tolerations:
    - key: workload
      operator: Equal
      value: monitoring
      effect: NoSchedule

prometheus:
  prometheusSpec:
    nodeSelector:
      agentpool: monitoring
    tolerations:
      - key: workload
        operator: Equal
        value: monitoring
        effect: NoSchedule
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    retention: 7d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: managed-csi
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      agentpool: monitoring
    tolerations:
      - key: workload
        operator: Equal
        value: monitoring
        effect: NoSchedule
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: managed-csi
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

kube-state-metrics:
  nodeSelector:
    agentpool: monitoring
  tolerations:
    - key: workload
      operator: Equal
      value: monitoring
      effect: NoSchedule

prometheus-node-exporter:
  tolerations:
    - operator: Exists

grafana:
  enabled: false

kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false